spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        created-message:
          destination: created-message
          contentType: application/json
        create-message:
          destination: create-message
          contentType: application/json